### ISSUE TITLE
Анализ и валидация кода

### ISSUE THREAD

**Issue by kizu** [css/csso#11]
Раз уж всё-равно весь CSS парсится, почему бы с каким-нибудь ключиком не выдавать всякую полезную информацию о коде?

Ну, например:
1. Если селекторов больше 4095 — выдавать предупреждение, что в ие дальше какого-то селектора будут проблемы (как вариант — сразу предлагать засплитить файл).
2. Пытаться отлавливать всякие ошибки (если этого до сих пор нет), которые могут привести к чему-нибудь плохому (многое из того, что w3cшный валидатор делает)
3. Сообщать о всяких неоптимальных селекторах, влияющих на производительность (ховеры без элементов, звёздочки, cелектор + без родителя/элементов (опасно в фф <4) и т.д.)

В общем, попробовать в будущем сделать не просто оптимизатор, но и анализатор кода, кажется, это может быть вполне разумным развитием :)

**Comment by lahmatiy** [comment]
Agree, those tasks are for another utility.
