### ISSUE TITLE
Convert rgba with no transparency to rgb

### ISSUE THREAD

**Issue by ionian-wind** [css/csso#122]
What I have:
```css
rgba(255,255,255,1)
```
What I've got:
```css
rgba(255,255,255,1)
```
What I want:
```css
rgb(255,255,255)
```

**Comment by lahmatiy** [comment]
I believe nobody use it as a hack. Only very old browsers don't support for `rgba`. And better use some other more universal hacks for those browsers.

**Comment by lahmatiy** [comment]
Now `csso` converts `rgba(255,255,255,1)` to `#fff`.
