### ISSUE TITLE
Something unclear, but definitely wrong

### ISSUE THREAD

**Issue by pepelsbey** [css/csso#132]
According to diff, csso is messing up with typical `reset.css` (which is quite widely used) at the top of the `before.css`:

![top](https://f.cloud.github.com/assets/105274/686929/0aacd6de-da6b-11e2-816f-e40f711af498.png)

And just removing `transform-origin:0 0` and `transform:scale(2)` at the bottom

![bottom](https://f.cloud.github.com/assets/105274/686932/2ec965fa-da6b-11e2-85dc-5acc0d5ad290.png)

See `before.css` and `after.css` — https://gist.github.com/pepelsbey/5830760

**Comment by lahmatiy** [comment]
Could you clarify what is actually wrong (on minimal css fragment)? Is it reproducing on last version?

**Comment by pepelsbey** [comment]
Wow, 3 years later! Will test it again :)

**Comment by lahmatiy** [comment]
Why not? Time to close all those issues ;)
