### ISSUE TITLE
Incorrect processing of CR LF

### ISSUE THREAD

**Issue by Taritsyn** [css/csso#147]
When processing of the following CSS code (intentionally contains an error):

	@charset "UTF-8";

	html {
		background-color: #e2e2e2;
		margin: 0;
		padding: 0;
	}

	body {
		background-color: #fff;
		border-top: solid 10px #000;
		color: #333;
		font-size: .85em;
		font-family: "Segoe UI", Verdana, Helvetica, Sans-Serif;
		margin: 0;
		padding: 0;
	}

	a {
		color: #333;
		outline: none;
		2padding-left: 3px;
		padding-right: 3px;
		text-decoration: underline;
	}

If `\r\n` (CR LF) is used as a newline character, then the following error is displayed:

	Please check the validity of the CSS block starting from the line #59 

If `\n` (LF) is used as a newline character, then the following error is displayed:

	Please check the validity of the CSS block starting from the line #30 

Thus, we get a different line numbers depending on which type of newline character is used.

**Comment by lahmatiy** [comment]
Fixed by 8a66cfa252a8ed6c30d97e062a6b05e468dc7cc8
