### ISSUE TITLE
Merging selector not always working

### ISSUE THREAD

**Issue by tomap** [css/csso#155]
When I compress this only:

 .fc-header .fc-button{margin-bottom:1px;vertical-align:top;}
 .fc-header .fc-button{margin-right:1px;}

the result is:

.fc-header .fc-button{margin-bottom:1px;vertical-align:top;margin-right:1px}

But with this larger piece of code:

.fc-header .fc-button{margin-bottom:1px;vertical-align:top;}

.fc-header .fc-button{margin-right:1px;}

.fc-state-hover,.fc-state-down,.fc-state-active,.fc-state-disabled{color:#333;background-color:#e6e6e6}
.fc-state-hover{color:#333;text-decoration:none;background-position:0 -15px;-webkit-transition:background-position .1s linear;-moz-transition:background-position .1s linear;transition:background-position .1s linear;}

.fc-state-down,.fc-state-active{background-color:#ccc;background-image:none;outline:0;box-shadow:inset 0 2px 4px rgba(0,0,0,.15),0 1px 2px rgba(0,0,0,.05)}
.fc-state-disabled{cursor:default;background-image:none;opacity:.65;filter:alpha(opacity=65);box-shadow:none}
.fc-event{border:1px solid #3a87ad;background-color:#3a87ad;color:#fff;font-size:.85em;cursor:default}

It's not working anymore:

.fc-header .fc-button{margin-bottom:1px;vertical-align:top}.fc-header .fc-button{margin-right:1px}.fc-state-hover,.fc-state-down,.fc-state-active,.fc-state-disabled{color:#333;background-color:#e6e6e6}.fc-state-hover{color:#333;text-decoration:none;background-position:0 -15px;-webkit-transition:background-position .1s linear;-moz-transition:background-position .1s linear;transition:background-position .1s linear}.fc-state-down,.fc-state-active{background-color:#ccc;background-image:none;outline:0;box-shadow:inset 0 2px 4px rgba(0,0,0,.15),0 1px 2px rgba(0,0,0,.05)}.fc-state-disabled{cursor:default;background-image:none;opacity:.65;filter:alpha(opacity=65);box-shadow:none}.fc-event{border:1px solid #3a87ad;background-color:#3a87ad;color:#fff;font-size:.85em;cursor:default}

I'm not sure why!

I'm using windows so my command line is:

C:\fullcalendar>node C:\Users\username\AppData\Roaming\npm\node_modules\csso\lib\csso.js fullcalendar.src.css fullcalendar.min.css

I've tested with your web interface, and the issue can also be reproduced:
http://css.github.io/csso/csso.html

Thomas P.

**Comment by lahmatiy** [comment]
Looks like issue was solved in `1.5.0`
