### ISSUE TITLE
Remove duplicate properties

### ISSUE THREAD

**Issue by fronteed** [css/csso#167]
Exact dublicates sometimes aren't removed.

Here's a test case with `display: block`, checked on http://css.github.io/csso/csso.html

Input:

```
.b {
  position: relative;
  display: block;
  display: block;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  display: block;
  overflow: hidden;
  text-indent: 100%;
  white-space: nowrap;
}
```

Output:
```
.b{position:relative;display:block;display:block;text-overflow:ellipsis;display:block;overflow:hidden;text-indent:100%;white-space:nowrap}
```

There're 3 instances of `display: block` in the output code.

**Comment by lahmatiy** [comment]
As I found, `display` merge was disabled. It was hardcoded to solve #71
But this restriction isn't needed anymore, since new approach merge properties more accurate.
