### ISSUE TITLE
Add SourceMap support

### ISSUE THREAD

**Issue by hsablonniere** [css/csso#173]
Hi,

It would be great if csso could consume existing SourceMaps and produce a new one.

Thx.

**Comment by zackcote** [comment]
:+1: i'd love to see this soon.

**Comment by JetFault** [comment]
+1 clean-css recently added support for sourcemaps https://github.com/jakubpawlowicz/clean-css/issues/125

**Comment by tadatuta** [comment]
guys, there's no reason to use CSSO anymore — `clean-css` compresses almost as well as CSSO but much faster. so we decided to stop the development

**Comment by contra** [comment]
@tadatuta Maybe that should be in the README of the project then so people don't waste their time. Would also be good to give a heads up to anybody who has written something like gulp or grunt-csso so they can also put a label on their READMEs

**Comment by zackcote** [comment]
@contra :+1:

**Comment by ben-eb** [comment]
@tadatuta I'm in agreement with @contra, if you decide to stop development of CSSO then that would be unfortunate. CSSO has some very good structural minimisation options which mean that the generated CSS can be much smaller than other minifiers. But, if you think it isn't worth continuing development it would be good to see an official word on the README, recommending that people use another tool.

Personally I think minifiers should be *thorough*, not *fast*. I would rather shave the extra 10 bytes and be waiting 10 seconds for it, if that meant my stylesheet was as optimised as it could be.

**Comment by jakubpawlowicz** [comment]
@tadatuta Thanks for clean-css endorsement!
@ben-eb You may want to look at clean-css 3.1 which added restructuring on par with csso, so you should get comparable or better minification - https://github.com/jakubpawlowicz/clean-css/blob/master/History.md#310--2015-02-26

**Comment by ben-eb** [comment]
@jakubpawlowicz Thanks - am already using clean-css for a couple of projects. I'd say it was one of the better projects out there, but I've found all minifiers currently out there fail on certain cases, some can compress a file better than others (but this sometimes means breakage).

I'm currently working on a project to help bugfix issues, which runs through test cases and can identify broken/optimal output, in the hope that it can be of some use. The project code needs tidying up a bit, and some kind of report should be generated from it, but at the moment it has 74 tests. Will look at publishing soon.

**Comment by jakubpawlowicz** [comment]
Would be great to see it. We should all aim for 100% compatibility but testing for breakages is tricky.

**Comment by sdaitzman** [comment]
:+1:

**Comment by cklanac** [comment]
2 things...

1) @tadatuta said they stopped development, but it looks @lahmatiy has restarted development again in October (kudos @lahmatiy). 

2) I was able to get source maps to work by calling it before sourcemaps.write(). Note, I'm using `gulp-ruby-sass`, so I'm not sure it this works with `gulp-sass`.

```
var gulp = require('gulp');
var $ = require('gulp-load-plugins')();

gulp.task('sass', function () {
  return $.rubySass('public/assets/css/main.scss', { sourcemap: true })
    .on('error', console.error.bind(console, 'Sass error:'))
    .pipe($.if('*.css', $.csso()))
    .pipe($.rename({suffix: ".min"}))

    // For inline sourcemaps
    //.pipe($.sourcemaps.write())

    // For file sourcemaps
    .pipe($.sourcemaps.write('.', {
      includeContent: false
    }))

    .pipe(gulp.dest('public/assets/css'));
});
```

**Comment by lahmatiy** [comment]
@cklanac SourceMaps will be supported as soon as the switch to a new parser (in development). But before this compressor should be reworked (see progress in [compressor](https://github.com/css/csso/tree/compressor) branch).

**Comment by shane805** [comment]
+1

**Comment by paulirish** [comment]
@lahmatiy since the compressor branch is now kaput, what's the status update for source maps?

**Comment by lahmatiy** [comment]
@paulirish It almost done, see [source-maps](https://github.com/css/csso/tree/source-maps) branch. Last issue need to be fixed and it's ready for landing. Release is planning later today or tomorrow.

**Comment by paulirish** [comment]
Oh wow. :) Good timing, then. Thanks for all the awesome work!

**Comment by lahmatiy** [comment]
Boom! It's done :)
https://github.com/css/csso/releases/tag/v1.6.0
