### ISSUE TITLE
compress an entire directory through command line

### ISSUE THREAD

**Issue by ghost** [css/csso#190]
Is it not possible to compress an entire directory in one go using command line?

With stylus I'd do:

```
sudo stylus styl -c -o ../css
```

I don't see the option to do something similar here.

**Comment by lahmatiy** [comment]
Duplicate #97

**Comment by lahmatiy** [comment]
I believe that the file concatenation task is for task runners. Btw, CLI was extracted into separate project and the issue isn't relevant for this repo anymore, sorry.
