### ISSUE TITLE
"@license" | "@preserve" to keep comments please

### ISSUE THREAD

**Issue by tomByrer** [css/csso#199]
Google Closure, & a few other [minifiers](https://github.com/mishoo/UglifyJS2#usage)  use JSDoc-style comment flags (`@license` `@preserve`) to keep a comment block.  I like to include the British & capital spellings in the RegEx [`/@[Ll]icen[sc]e|@[Pp]reserve/`](http://regexr.com/38nul) to catch them all.

Not breaking, perhaps add when a [comment bug is fixed](https://github.com/css/csso/issues/194).

**Comment by lahmatiy** [comment]
#194 is closed now
Can you provide example of comment with `@license`/`@preserve`? I'm not sure I saw it in CSS.

**Comment by tomByrer** [comment]
I can't find any off hand; x-doc style comments tend to be more in JS land.  I wanted to promote @license at a [CDN](http://www.jsdelivr.com/?query=css&limit=20) I help out with on occasion.  (many use `/*! though; thanks).
I'll close for now, & reopen if I find a bunch of real-world cases.
Thanks.
