### ISSUE TITLE
Hanging on processing

### ISSUE THREAD

**Issue by mkstvnsn** [css/csso#201]
Excellent project. I'm having an issue with the optimizer hanging when more data is inputted. Trying to determine the maximum but it appears after either a certain character count or if the program is hitting "something" it fails to deliver a result. Has anyone else experienced this?

It works fine if I drop in chunks of ~250-300 lines of CSS, but after that it does not work for me. Of course the power in this would be making large CSS files smaller... Any advice?

Thank you!

**Comment by grrowl** [comment]
I'm seeing this issue too on a 2600 line fine (one of those, "each selector and rules on one line only" deals).

Since the line it errors on jumps around based on various things (although seemingly always before an `#id` selector), I'll try breaking it up into smaller files.

**Comment by grrowl** [comment]
The errors were *much* earlier than the line stated, running through CSSLint shed some light on the issue.

**Comment by lahmatiy** [comment]
@josx your file is really huge – it's about 3.7Mb and any tool has trouble with it. Moreover I found 1 (!!) rule that takes 2.1Mb (56% of file) and contains 20873 selectors to set single property `background-color`. It's very very strange. May be something wrong with css generation?
`csso` is not hanging in this case, but it takes too many time to done. Probably it's never to be finished.
Anyway we'll use this file example as stress test for future implementations if there are no objections

**Comment by josx** [comment]
@lahmatiy thanks a lot!
I forgot to write down here, but there was a problem in a less code when generating this file.
Anyways As you said might be usefull to know why it is happening.
Go head and use it!

**Comment by lahmatiy** [comment]
@josx Good news: reworked version of compressor (could be found on `compressor` branch) is not hanging anymore. It takes about 30sec on my Mac, but outputs the result :)

**Comment by josx** [comment]
good catch! thanks a lot!
So We can close this issue now.

**Comment by lahmatiy** [comment]
I'll do when new release is out.

**Comment by lahmatiy** [comment]
Also I see some places for optimisations that could help drop time down. Stay tuned ;)

**Comment by lahmatiy** [comment]
csso 1.5 is out, problem fixed.
Compression takes about 12 seconds now.

**Comment by josx** [comment]
@lahmatiy 
Great!
Thanks for your time and effor!

**Comment by lahmatiy** [comment]
csso 1.6 is out
Compression takes ~5.5 seconds now :)
