### ISSUE TITLE
Add missing @charset when file contains non ASCII characters

### ISSUE THREAD

**Issue by paazmaya** [css/csso#219]
As a feature request and since there is a removal for invalid `@charset`, would it be possible to add the `@charset` rule when it is not defined and the given file contains characters that are outside the ASCII range?

**Comment by lahmatiy** [comment]
CSSO is about removing, not adding or fixing something. Believe the task you talking about is for another tool. Sorry.

**Comment by paazmaya** [comment]
@lahmatiy thank you for the clarification. Please have some :grapes:, my treat!
