### ISSUE TITLE
Namespaced attribute selectors throw csso off

### ISSUE THREAD

**Issue by regiskuckaertz** [css/csso#233]
Hello, I noticed than with the following CSS:

```
@namespace xlink "http://www.w3.org/1999/xlink";
use > use[xlink|href="#il-"] {
  stroke: currentColor;
}
```

csso returns with the following error message: Cannot read property '0' of undefined

I'm using grunt-csso which uses the latest version of csso (1.3.11). The same error happens when I type `[*|href="..."]` as well.

**Comment by lahmatiy** [comment]
Yep, csso parser didn't support for namespaces in attribute selectors.
Fixed.
