### ISSUE TITLE
(Improvement) Tests needed for bug in version 1.4.0

### ISSUE THREAD

**Issue by cnole** [css/csso#247]
We used csso through gulp-csso to minify our CSS and we rolled out a release on Monday (19/10/2015). Unfortunately there was a bug in csso version 1.4.0 which was used to build the release. The bug is reproducible:

```shell
echo ".test { color: #000; } .test * { color: #fff; }" | ./csso
```
which produces the following output:
```css
.test{color:#000}.test*{color:#fff}
```

As you can see the whitespace before the wildcard selector "*" was removed, that is wrong output and can be very dangerous because the whole cascading styles under ".test" are lost. 

The version 1.4.1 produces the following output which is exactly i would expect:

```css
.test{color:#000}.test *{color:#fff}
```
I appreciate a lot that you have fixed this bug so quickly in version 1.4.1. Could you please write some tests for this case so that this won't happen again?

**Comment by lahmatiy** [comment]
It was added with fix, see commit https://github.com/css/csso/commit/dd8709eec3acd59eb791fb1608f49fc68cb7c783

**Comment by cnole** [comment]
@lahmatiy My Bad, i didn't see the commit. Thank you so much.
