### ISSUE TITLE
node --use_strict command is not compatible with csso

### ISSUE THREAD

**Issue by Joffrey** [css/csso#252]
Sometimes, I use special keywords (let,const,etc) which need the strict mode.
I launch nodejs in this following way : **node --use_strict**

But csso is not compatible with that, and I get this error:
```
C:\programs\nodejs\node_modules\csso\lib\parser\tokenize.js:49
        tokens.push(x = {
                      ^
```

**Comment by lahmatiy** [comment]
Thank you for report. Fixed.
