### ISSUE TITLE
Incorrect minification of TRBL properties with common keywords (inherit, unset etc)

### ISSUE THREAD

**Issue by antoinebrault** [css/csso#255]
"inherit" can only be applied to all margin properties, not individually.

See http://www.w3.org/TR/CSS2/box.html#margin-properties
'margin' Value:  	< margin-width >{1,4} | inherit
as opposed to 
'margin' Value:  	(< margin-width > | inherit) {1,4}
```
echo md-radio-group.layout-row md-radio-button { margin-top: 0; margin-bottom: 0; margin-left: inherit; margin-right: 16px; } | csso

md-radio-group.layout-row md-radio-button{margin:0 16px 0 inherit}
```
Chrome rejects "margin:0 16px 0 inherit"

**Comment by lahmatiy** [comment]
Yep, you're right.
It's also applies for other common values like `unset` and `initial` http://www.w3.org/TR/css3-values/#common-keywords

**Comment by joningib** [comment]
What's up with this bug? Is this being fixed?

**Comment by lahmatiy** [comment]
Yep, bug will be fixed.
Thank you for ping.
