### ISSUE TITLE
1.5.2 release is not working correctly when installed from npm

### ISSUE THREAD

**Issue by domakas** [css/csso#265]
It seems that npm release tarball http://registry.npmjs.org/csso/-/csso-1.5.2.tgz and github release tarball https://github.com/css/csso/archive/v1.5.2.tar.gz are different. In particular when optimizing with npm release version lots of bulk data is outputted to console. This is done in particular with one method:

```js
// File: csso/lib/compressor/restructure/markShorthands.js
TRBL.prototype.isOkToMinimize = function() {
    //...//
            console.log(values); // <-- line 194
    //...//
};
``` 

I'm not able to find anything in git history regarding this, and 1.5.1 release seem to have correct behavior.

I have no idea how to solve this, maybe try to create new release or something like updating npm registry. However this causes thousands of lines outputted in build log, which is then unreadable :(

**Comment by lahmatiy** [comment]
Thank you for notice. You're right, one of modules was published in development state.
I've published 1.5.3. Should be ok now.
