### ISSUE TITLE
Bump major version for node.js 0.10 support drop

### ISSUE THREAD

**Issue by triccardi-systran** [css/csso#275]
Since 1eeec74b7369af0ab65912dcc015ed4bfbcfad9c node.js 0.10 is not officially supported anymore.

I believe this is a breaking change, and if `csso` follows semver then this should have released as 2.0.0, with a major version bump (because npm itself doesn't filter by engine version compatibility before resolving by semver constraints). 
(If `csso` doesn't follow semver then it should be stated in the README to inform its users not to use semver operators such as `^` when depending on `csso`.)

In practice, node.js 0.10 compatibility was broken with 9f631d360cf9a555d9b1db3ea76043c2ff16a739 (it depends on `Map`), and was released starting 1.6.0.

I understand it's too late to change that because it would require unpublishing 1.6.0 and 1.6.1, or re-implement 1.6.0 features with node.js 0.10 support, both options being probably not wanted.

So maybe simply add a warning in the README, stating that node.js 0.10 is officially supported for versions < 1.4.0 (and maybe with no future maintenance), it will inform parent projects which may want to branch themselves for support of node.js 0.10.

Concrete issue:
`gulp-csso` depends on `csso ^1.4.0`, which worked with node.js 0.10 until last week when `csso` 1.6.0 was published, and there is no easy way to force an old version of `csso` without forking `gulp-csso`.

I intend to open an issue on `gulp-csso` to suggest a node.js 0.10 branch, with different solutions depending on the responses here.

**Comment by lahmatiy** [comment]
Truly speaking, till this issue I didn't know that `0.10` drop is the problem. I thought `0.10` is too old and nobody use it already. But I think you're right and we should delay this change until major release.
Fortunately changes are not so dramatic and `0.10` support is possible with small fixes. I'm trying fix it and publishing `1.6.2`.

**Comment by lahmatiy** [comment]
New version is published.
Should be ok now

**Comment by triccardi-systran** [comment]
A big thank you, I wasn't expecting support for node 0.10 !

`0.10` is indeed old, but it's still officially supported by the node.js foundation until 2016-10-01, see https://github.com/nodejs/LTS#lts_schedule

Thanks again.

**Comment by lahmatiy** [comment]
Welcome!
And thank you for information about node.js 0.10 (didn't know it's LTS version).
