### ISSUE TITLE
Option for removing special comments

### ISSUE THREAD

**Issue by meritt** [css/csso#285]
Based on Twitter discussion https://twitter.com/cssoptimizer/status/710785972255006720.

I think to remove special comments or to keep them should be users decision. In some cases it would be great to use this option. It can be disabled by default.

**Comment by lahmatiy** [comment]
Available in [2.1.0](https://github.com/css/csso/releases/tag/v2.1.0)
Use `csso --comments none` or `csso.minify(css, { comments: false })`

**Comment by meritt** [comment]
Thanks.
