### ISSUE TITLE
0% minification

### ISSUE THREAD

**Issue by MohammadYounes** [css/csso#286]
Zero percent length is left AS IS, which not only adds extra character but also messes N-Value syntax minification.

| Input | Actual | Expected |
| --- | --- | --- |
| `margin:0%` | `margin:0%` | `margin:0` |
| `margin:0% 0px 0em 0rem` | `margin:0% 0 0` | `margin:0` |

Thanks!

**Comment by RubaXa** [comment]
@MohammadYounes done 🎉

**Comment by MohammadYounes** [comment]
@RubaXa Thanks!

**Comment by lahmatiy** [comment]
3.4.0 is out with this feature on board.

**Comment by RubaXa** [comment]
@lahmatiy пятница же, спать надо, а не минор поднимать 🌝
