### ISSUE TITLE
Quote URLs

### ISSUE THREAD

**Issue by kurtextrem** [css/csso#287]
https://drafts.csswg.org/css-values/#urls
"For legacy reasons, a <url> can be written without quotation marks around the URL itself. This syntax is specially-parsed, and produces a <url-token> rather than a function syntactically"
For me that sounds like the rendering engine has more work to do to parse those. Why not add 2 bytes for better perf?

**Comment by lahmatiy** [comment]
I think it doesn't make sense until nobody measured unquoted urls usage impact on performance.

**Comment by kurtextrem** [comment]
I'd love to do the benchmark, but I'm not sure how I can benchmark CSS props.

**Comment by lahmatiy** [comment]
Closing until any details about effect on performance if any.
