### ISSUE TITLE
IE 11 -  bug after minification

### ISSUE THREAD

**Issue by MariskaS** [css/csso#289]
Hello!
There is a bug after minification, which can be seen only in IE (eg IE11)
![bug](https://cloud.githubusercontent.com/assets/5942101/14116562/066755bc-f5e9-11e5-8313-1196dc7f21b7.png)

**Comment by lahmatiy** [comment]
1.8.1 is out with bug fix

**Comment by MariskaS** [comment]
Thank you!)
