### ISSUE TITLE
so confused with the error "[TypeError: error.setMessage is not a function]"

### ISSUE THREAD

**Issue by xblxc** [css/csso#293]

**Comment by zalgocykel** [comment]
What version are you using? Updating to latest version fixed it for me

**Comment by lahmatiy** [comment]
I suppose you see that message when using `postcss-csso`, I'm right?
Issue was fixed in `postcss-csso` [1.1.2](https://github.com/lahmatiy/postcss-csso/releases/tag/v1.1.2) yesterday. It also may require update `csso` to 2.1

**Comment by xblxc** [comment]
yes, it's postcss-csso, and the version is 1.1.1. All is right when I update it, thanks~~
