### ISSUE TITLE
ERROR in Cannot find module './prepare/AppActions.js'  

### ISSUE THREAD

**Issue by puruzio** [css/csso#294]
I'm getting the following error as I bundle my js and css with Webpack.

    ERROR in Cannot find module './prepare/AppActions.js'
     @ ./components/filename.css 4:14-84

This error occurs no matter which css file I import, which makes me think it's caused by csso, rather than the css files. Also, I did a text search on all files in the project, and found prepare/AppActions.js in css-browser.js.

=================== Grid_component.js that imports the css file
var LinkedStateMixin = require('react-addons-linked-state-mixin');
import {AgGridReact} from 'ag-grid-react-component';
import moment from 'moment';
var myConst = require('../actions/myConst');
import Purger from '../components/Purger';
import './filename.css';
import './theme-fresh.css';

====================
Here is a little more info on my dev environment.

npm -v 3.8.0
webpack 1.13
    : css loader defined as  { test: /\.css$/, loader: "style-loader!css-loader" }
node -v v5.3.0

**Comment by lahmatiy** [comment]
Are you sure issue is related to CSSO? Since optimizer just process CSS (string) but doesn't locate files or load their content by itself.
How do you use CSSO? (e.g. as some plugin or clean csso)

**Comment by lahmatiy** [comment]
> Also, I did a text search on all files in the project, and found prepare/AppActions.js in css-browser.js.

Oh, I missed this one when read before. I know for sure `prepare/AppActions.js` can't to be in `dist/csso-browser.js` – it's really strange. Also `csso-browser.js` is for using `CSSO` in browser environment only (for example https://css.github.io/csso/csso.html) and never to be used for compression in build pipeline.
Looks like something wrong with your webpack config. Please provide config part where you are set up CSSO. As I know `style-loader`/`css-loader` aren't using for `CSSO`.

**Comment by puruzio** [comment]
This is all I have in webpack.config.js. There is nothing specific to csso. I wonder if ag-grid somehow uses it, but not sure how it can create this issue.

var path = require('path');
var webpack = require("webpack");

module.exports = [
    {
        name: "browser",
        entry: {
            main: './ng-react-jo.jsx'
        },
        output: {
            path: '.',
            filename: 'bundle.js'
        },
        debug: true,
        devtool: "source-map",
        watch: true,
        resolve: {
            alias: {
             "ag-grid-root" :  path.join(__dirname , "../../../node_modules/ag-grid/dist/styles") //
            }
        },
        module: {
            loaders: [
                {
                    test: /\.jsx?$/,
                    loader: 'babel-loader',
                    exclude: /node_modules/,
                    query: {
                      presets: ['es2015', 'react']
                    },
                },
                {
                    test:    /\.elm$/,
                    exclude: [/elm-stuff/, /node_modules/],
                    loader:  'elm-webpack',
                  },
                { test: /\.css$/, loader: "style-loader!css-loader" }
            ]
        },
        externals: {
            "jquery": "jQuery"
        }
    }
];

**Comment by lahmatiy** [comment]
You can try `npm list` to find out which dependancy using for CSSO

**Comment by puruzio** [comment]
Looks like css-loader uses it.

├─┬ css-loader@0.23.1
│ ├─┬ cssnano@3.5.2
│ │ ├─┬ postcss-svgo@2.1.3
│ │ │ ├─┬ is-svg@2.0.0
│ │ │ │ └── html-comment-regex@1.1.0
│ │ │ └─┬ svgo@0.6.6
│ │ │   ├─┬ coa@1.0.1
│ │ │   │ └── q@1.4.1
│ │ │   ├─┬ **csso@2.0.0**
│ │ │   │ └─┬ clap@1.1.0
│ │ │   │   └── chalk@1.1.1

**Comment by lahmatiy** [comment]
Yep, csso is using by svgo, that used cssnano, that used by css-loader. But I don't understand how does it connect with your issue.
Probably you use some extensions in your `components/filename.css`

**Comment by puruzio** [comment]
This happens with any css file I load so the issue is not specific to any particular css file.

**Comment by lahmatiy** [comment]
I don't know how to help you. But for sure it's not a CSSO related bug.
