### ISSUE TITLE
Removes styling when restructure is set to true

### ISSUE THREAD

**Issue by bjarnef** [css/csso#295]
It seems the gulp plugin removes styling from css when `restructure: true`

In Bootstrap 3.3.5+ the following has been adding to dropdowns.less

```
// Dropdown arrow/caret
.caret {
  display: inline-block;
  width: 0;
  height: 0;
  margin-left: 2px;
  vertical-align: middle;
  border-top:   @caret-width-base dashed;
  border-top:   @caret-width-base solid ~"\9"; // IE8
  border-right: @caret-width-base solid transparent;
  border-left:  @caret-width-base solid transparent;
}
```
https://fossies.org/diffs/bootstrap/3.3.4_vs_3.3.5/less/dropdowns.less-diff.html

However when csso is enabled or `restructure: true` it removes the first `border-top` line from output, e.g.
```
border-top: 4px solid\9;
```
but is should be:
```
border-top: 4px dashed;
border-top: 4px solid\9;
```
It has also been disqussed in csso here https://github.com/css/csso/issues/231
but it should have been fixed here https://github.com/css/csso/commit/87c715836c61980167ea67413717fd436ed93801

and marked as fixed in v. 1.4.0
https://github.com/css/csso/releases/tag/v1.4.0 (see *don't merge \9 hack values (#231)*)

but it doesn't work in latest version of gulp-csso (2.0.0).
not sure if something isn't included from csso?

https://github.com/ben-eb/gulp-csso/issues/25

**Comment by lahmatiy** [comment]
CSSO 2.1.1 fixes issue

**Comment by bjarnef** [comment]
Thanks for the quick fix! :) 
👍
