### ISSUE TITLE
Пересчёт z-index

### ISSUE THREAD

**Issue by afelix** [css/csso#30]
В CSS нередко встречаются "условно" большие `z-index`, когда верстальщик пишет "лишь бы большой", например, `z-index: 9999`. В погоне за байтами есть смысл собирать `z-index` по коду и вместо `1000, 2000, 9999` сжимать до `1, 2, 3`.

**Comment by lahmatiy** [comment]
The optimisation is quite dangerous and has negligible effect. I believe there are no reasons to implement it.
