### ISSUE TITLE
TypeError: csso.justDoIt is not a function

### ISSUE THREAD

**Issue by nrnaveen0492** [css/csso#300]
TypeError: csso.justDoIt is not a function/vagrant/xperteamv2/node_modules/bundle-up/lib/css.coffee:23
      return csso.justDoIt(code);

**Comment by lahmatiy** [comment]
`justDoIt()` was removed in `2.0`. Use [`minify()`](https://github.com/css/csso#minifysource-options) instead or version prior `2.0`
