### ISSUE TITLE
Converting into shorthand has the potential to introduce **breakage**

### ISSUE THREAD

**Issue by thierryk** [css/csso#302]
Let's imagine this scenario:

**The HTML**

```
<div class="module news">
   ...
</div>
```

**The CSS:**

```
.module {
    background-color: #fff;
}
.news {
    background-image: url('smiley.gif');
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-position: center;
}
```

If **gulp-shorthand** converts the above into this:

```
.module {
    background-color: #fff;
}
.news {
  background: url('smiley.gif') no-repeat fixed center;
}
```

Then `.news.module` will end up with a **transparent** background color (instead of white) because the shorthand rule "resets" the value of `background-color` to its initial `value`&mdash;which is `transparent`.

**Comment by lahmatiy** [comment]
`CSSO` has no connections with `gulp-shorthand`. Please, post an issue to related project (https://github.com/kevva/gulp-shorthand).

**Comment by thierryk** [comment]
Really sorry about this. I'll do, thanks!
