### ISSUE TITLE
Bad code style notifier

### ISSUE THREAD

**Issue by Kalinin** [css/csso#309]
I have styles

```
.a{width: 10px;}
...
.a{width: 20px;}
```

Is is obvious that first selector unused.
I search for a tool that give me information about such places in css.
eg `getUnusedRule(styles)` -> line number at style.css, rule, selector, smth. else.

The second case is to notify about too nested selectors 
`.a .b .c .d{...}`
`getTooLongSelectors(styles, maxNestingNum)` -> info to find place in source code

Some other cases present.

I dont want to minify output css, but need to find such places in code and fix it manually.
The point is **not to minify** code, but to make source code more accurate for the better maintenance and to prevent pile unnecessary things.

Have you such plans? Or it realized already?

**Comment by lahmatiy** [comment]
Something like that is planning. Generally to notify about CSS that always removes on minification and probably a dead code.
But I think you're searching for [stylelint](http://stylelint.io/). I'm not sure but looks like this tool fit your needs.
