### ISSUE TITLE
Improper handling of CSS variables

### ISSUE THREAD

**Issue by kizu** [css/csso#318]
See http://dabblet.com/gist/b858218ff715b9b493ab4b93de89ec4b

Right now when there is a declaration consisting of only whitespace, CSSO drops it altogether, while for CSS variables they're meaningful:

``` CSS
.test_declared {
  --bar: ;
}
```

This declaration shouldn't be dropped, and the space shouldn't be removed (if there is whitespace, I think it should be minified to just one space).

Also, fallbacks for variables also have meaningful whitespace: `var(--foo, )` is not the same as `var(--foo,)`, so the space shouldn't be removed there (CSSO removes it ATM).

**Comment by lahmatiy** [comment]
Thank you for very interesting details 👍 
I will think how to fix it.

**Comment by lahmatiy** [comment]
CSSO [3.0](https://github.com/css/csso/releases/tag/v3.0.0) is out, should be fine now.
