### ISSUE TITLE
Removing overlapping styles vs. browser hacks

### ISSUE THREAD

**Issue by andrey-hohlov** [css/csso#320]
Hi!

I have problem with minifying css that contains browser hack https://github.com/chmln/flatpickr/issues/487

Before:
```
.selector {
  width: 6ch;
  width: 7ch\0;
}
```

After:
```
.selector {width: 7ch\0;}
```

Is there way to exclude removing overlapping rules only for this block?

**Comment by lahmatiy** [comment]
Hi!

`\0` is the same hack as `\9` and others targets to old IE. Unfortunately support all of them is too hard. Therefore most minifiers supports `\9` hack only, because Bootstrap uses it. I think it would be better to change `\0` to `\9` in your CSS to fix minification issue for most minifiers.

**Comment by andrey-hohlov** [comment]
@lahmatiy unfortunately in this case \9 not work in IE11 :(

**Comment by andrey-hohlov** [comment]
Maybe we can add support for this hack?
I think it will be easy.
I found `\9` only in two places:

`/lib/compressor/restructure/4-restructShorthand.js:86`
```
switch (child.name) {
  case '\\9':
    iehack = true;
    return;
```

`/lib/compressor/restructure/6-restructBlock.js:93`
```
if (/\\9/.test(name)) {
  hack9 = name;
}
```

**Comment by lahmatiy** [comment]
> @lahmatiy unfortunately in this case `\9` not work in IE11 :(

And it shouldn't. According to http://codemug.com/html/css-hacks-for-ie6ie7ie8ie9-and-ie10/
```
color:red\9; /* works in IE6, IE7, IE8, IE9 */
color:red\0; /* works in IE8, IE9 */
```

**Comment by lahmatiy** [comment]
[2.3.1](https://github.com/css/csso/releases/tag/v2.3.1) is out with `\0` hack support

**Comment by andrey-hohlov** [comment]
Great! Thank you 👍
