### ISSUE TITLE
Consider separating CLI.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [css/csso#321]
Saves users the `clap` and `source-map` dependencies.  The five most popular dependents of `csso` (`svgo`, `gulp-csso`, `inline-source`, `lede`, and `node-minify`) do not make use of the CLI.

**Comment by lahmatiy** [comment]
I thought about it several times. Most likely it will happen in the next major release.

**Comment by lahmatiy** [comment]
CSSO [3.0](https://github.com/css/csso/releases/tag/v3.0.0) is out, CLI has beed extracted into separate package
