### ISSUE TITLE
Using .---someclass in code breaks output

### ISSUE THREAD

**Issue by nealoke** [css/csso#323]
Using a class like `---someclass` in a css file breaks the csso plugin. 

Error message
`CSS parse error global.css: Identifier is expected`

**Comment by lahmatiy** [comment]
Yep, according to spec it's wrong name for class. Why do need this sort of names?

**Comment by nealoke** [comment]
@lahmatiy didn't know that, it just makes sense in my opinion as i follow `.classname--modifier` so a global modifier would be `.---globalmodifierclass`.

**Comment by lahmatiy** [comment]
@nealoke For fun, I tried `---className` in some browsers:
- works fine in Chrome and Firefox
- doesn't work in Safari, IE and Edge (as expected per spec)

**Comment by nealoke** [comment]
@lahmatiy :p really didn't know that it was wrong to use this but super thanks that csso / you pointed it out :p 👍
