### ISSUE TITLE
Specificity calculation: Add support for more CSS selectors

### ISSUE THREAD

**Issue by strarsis** [css/csso#324]
https://github.com/css/csso/blob/6920da533612aaf6024642123c5b2dcaa67a210e/lib/compressor/restructure/prepare/specificity.js#L35

https://github.com/keeganstreet/specificity

**Comment by lahmatiy** [comment]
Currently functionality of solutions are the same, `keeganstreet/specificity` doesn't cover cases for new functional-pseudo (see https://drafts.csswg.org/selectors-4/#specificity-rules)
