### ISSUE TITLE
Errors on custom properties in `@supports`

### ISSUE THREAD

**Issue by sgomes** [css/csso#325]
CSSO seems to have trouble dealing with custom properties in `@supports`, making it hard to write conditional code depending on whether custom properties are supported.

Both

```css
@supports ( --custom-props: "yes" ) {
  .foo {
  }
}
```

and

```css
@supports ( color: var(--custom-prop) ) {
  .foo {
  }
}
```

produce a `CSS parse error: Identifier is expected`.

**Comment by lahmatiy** [comment]
Problem should be fixed with new version based on `csstree` parser.

**Comment by lahmatiy** [comment]
CSSO [3.0](https://github.com/css/csso/releases/tag/v3.0.0) is out, should be fine now.
