### ISSUE TITLE
Подружиться с gzip

### ISSUE THREAD

**Issue by afelix** [css/csso#34]
Чем плотнее CSSO сжимает, тем меньше работы gzip и тем хуже иногда сжатие пары CSSO+gzip. Т.к. алгоритм DEFLATE основан на повторяющихся последовательностях, CSSO следует составлять как можно более однообразные строки. Например, пересортировывать селекторы по алфавиту, в итоге `a, b { .. } .. b, a { .. }` превратится в `a, b { .. } .. a, b { .. }`.

**Comment by lahmatiy** [comment]
Most things are normalizing now. Selectors are sorting since `1.5`. Property are not sorting yet because there are some edge cases, but will do.
I think we could close issue.
