### ISSUE TITLE
Can you compare csso and cssnano and another tools like this?

### ISSUE THREAD

**Issue by a-x-** [css/csso#340]

**Comment by a-x-** [comment]
I found some benchmark: https://goalsmashers.github.io/css-minification-benchmark/

**Comment by lahmatiy** [comment]
It's outdated a little bit (csso 2.0 in benchmark, but it's 3.1.1 currently).
For more details, you can see 1 year old slides in English https://www.slideshare.net/basisjs/csso-compress-css-english-version.
More info in Russian: slides – https://www.slideshare.net/basisjs/presentations, videos – https://www.youtube.com/playlist?list=PLf0s9ihTnfHyGOoQ_7Urte2lBRrJzqRqa

**Comment by a-x-** [comment]
Thank you, Roman!
