### ISSUE TITLE
How to use csso with css-modules?

### ISSUE THREAD

**Issue by gajus** [css/csso#345]
There is a section about Scopes (https://github.com/css/csso#scopes). However, from reading it, I do not understand how is one supposed to use it in a css-modules + webpack setup.

I am using https://github.com/gajus/babel-plugin-react-css-modules implementation of CSS modules. In this setup, each component has its own style sheet.

The generated CSS contains component name as part of the class name, e.g.

```css
.styles___pagination-button___1dMOo.styles___next___2BxhK {}
.styles___pagination-button___1dMOo.styles___active___2sAsB {}
.styles___pagination-button___1dMOo.styles___active___2sAsB:hover {}

```

Here, the `.styles___pagination` is a prefix representing the component. `-button` is the style name within the component stylesheet.

I am assuming that CSSO could use this information to optimize scopes. However, has there been any work done to automate this?

**Comment by lahmatiy** [comment]
@gajus Yep, CSSO can use this information for better optimisation. However additional work is needed to make this possible. In particular build a full map of scopes. I'm not a CSS Modules user, so I did dive into the problem. It may be done by making a plugin for webpack or something like this. We discuss such plugin with others and found few hard places: it's not clear how `composes` and global names (e.g. `:global()`) should affect the resulting map. I'll be happy if anyone solve the problem.

**Comment by lahmatiy** [comment]
@gajus Awesome! Thank you for sharing!
