### ISSUE TITLE
minify removed some repetitive styles but those are important.

### ISSUE THREAD

**Issue by kbdsbx** [css/csso#347]
```css
display: block; /* for old browsers */
display: -webkit-flex; /* for safari */
display: flex: /* for newest */
```

but minified:
```css
display: block;
```

**Comment by lahmatiy** [comment]
@kbdsbx What version do you use? This issue was fixed a long time ago. I've tested right now in web interface, current version works as expected:
![screen shot 2017-07-26 at 14 55 44](https://user-images.githubusercontent.com/270491/28619762-b07b16f0-7212-11e7-923d-00d49d2da0dc.png)

**Comment by lahmatiy** [comment]
Closing issue for now, since your example works as expected. Fill free to reopen with problem example if any.
