### ISSUE TITLE
npm install failed in Windows

### ISSUE THREAD

**Issue by CauserLee** [css/csso#352]
When i run the command "npm install csso",it was failed with: 
 
npm ERR! Unexpected end of input at 1:16465
npm ERR! },"1.5.2":{"name":"csso","version":"1.5.2","dependencies":{"clap":"^1
npm ERR!           

Same command works in OSX

**Comment by lahmatiy** [comment]
I tried it myself it works find. Looks like problem with `npm` or `package-lock.json` (may it's corrupted)

Btw, as I see you use pretty old CSSO version 1.5.2, the latest version is 3.2.0

**Comment by CauserLee** [comment]
Problem solved as I changed the registry of my npm, looks like the json file is corrupted in the previous registry, thanks :)
