### ISSUE TITLE
generate both .min.css as regular .css with extract-text-plugin with one webpack call

### ISSUE THREAD

**Issue by stepet80** [css/csso#353]
Hello,

Through following thread I landed on this plugin:
https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/637#issuecomment-334623529

We are using extract-text-plugin to generate css. This plugin uses csso plugin. Is it possible to generate both a non minified css and a minified css? 

The reason I ask is that we use unminified-webpack-plugin to generate both min.js files and the regular .js files without having to call webpack multiple times with different options.

Or is it possible to write some custom code to have this done?

Thanks

**Comment by lahmatiy** [comment]
Yep, that's a responsibility of code/plugins that uses CSSO.
@stepet80, you should use csso-webpack-plugin or something like that to solve your problem.
