### ISSUE TITLE
PostCSS@6

### ISSUE THREAD

**Issue by a-x-** [css/csso#354]
`Error: Your current PostCSS version is 6.0.13, but postcss-csso uses 5.2.18.`

**Comment by lahmatiy** [comment]
CSSO doesn't use PostCSS. This issue should be moved to [postcss-csso](https://github.com/lahmatiy/postcss-csso). Looks like postcss-csso should update its dependency.

**Comment by a-x-** [comment]
ok, thank you: https://github.com/lahmatiy/postcss-csso/issues/11
