### ISSUE TITLE
Minifying 0px as var fallback in calc doesn't work

### ISSUE THREAD

**Issue by kanongil** [css/csso#355]
The following minifies the `0px` value to `0`, which breaks at least Safari:
```css
width: calc(1px + var(--not-there, 0px));
```

This is quite similar to issue #222, but is not handled by the fix due to encapsulation inside the `var()`.

**Comment by lahmatiy** [comment]
What version do you use?
I tried case with latest version, CSSO outputs `width:calc(1px + var(--not-there, 0px))`

**Comment by kanongil** [comment]
It seems my system is using an old version `v2.3.2`. If I try with the latest published release and everything is fine.

Sorry about the noise.
