### ISSUE TITLE
Don't rewrite selectors with escaped characters

### ISSUE THREAD

**Issue by jarek-foksa** [css/csso#357]
For example ```csso.minify(`span[data-value="\a"] {color: red;}`).css;``` will return `span[data-value="a"] {color: red;}`.

`\a` shouldn't be rewritten as `a` since the former one represents a line feed while the latter one a letter.

**Comment by lahmatiy** [comment]
What version do you use? Latest version returns `span[data-value=\a]{color:red}`

**Comment by jarek-foksa** [comment]
I'm using Csso v3.3.1 and Node.js v8.7.0.

**Comment by lahmatiy** [comment]
I understood the problem.

> `\a` shouldn't be rewritten as a since the former one represents a line feed while the latter one a letter

`\a` is not a line feed, but escaped `a` that means a regular `a` in result. Try this:

```cmd
~ node
> '\a'
'a'
```

To represent line feed you should use '\n', '\x0a' or `\u000a`:

```cmd
~ node
> '\n'
'\n'
> '\x0a'
'\n'
> '\u000a'
'\n'
```

So it's not a CSSO issue, but how JavaScript represents a special chars.

**Comment by lahmatiy** [comment]
If `span[data-value="\a"] {color: red;}` is original CSS, then you should escape backslashes when put CSS into JS string
```js
csso.minify(`span[data-value="\\a"] {color: red;}`).css;
// 'span[data-value=\\a]{color:red}'
// or in output
// span[data-value=\a]{color:red}
```

**Comment by lahmatiy** [comment]
Refinement for
> `\a` is not a line feed, but escaped `a` that means a regular `a` in result

It's true for JavaScript. Another rules in CSS, where `\a` is a line feed. It can be checked by `CSS.escape()`:

```js
CSS.escape('\n') // '\a '
```

**Comment by jarek-foksa** [comment]
Thanks for explanation, I didn't realize JS and CSS use different rules when it comes to character escapes.

I managed to resolve this issue by always using `\\a` to represent new lines in CSS files.

In JS things can get a lot more complicated, for example the equivalent of `element.matches('span[data-value="\\a"]')` is `element.getAttribute("data-value") === "\n"`.
