### ISSUE TITLE
Is it redundant to use Autoprefixer with csso?

### ISSUE THREAD

**Issue by JWess** [css/csso#359]
Does csso handle vendor prefixes? Is it pointless to use Autoprefixer before passing its results to csso?

**Comment by lahmatiy** [comment]
CSSO does nothing with vendor extensions, i.e. doesn't remove any of them. It uses universal rules for merging and value optimisations that apply to vendor properties too, but doesn't check that the property is outdated. Therefore, using Autoprefixer before CSSO is make sense at the moment.
