### ISSUE TITLE
unquoted background url with query part

### ISSUE THREAD

**Issue by rifler** [css/csso#360]
What's wrong with it? If I put url in quotes, then everything is ok
```
Message:
    postcss-csso: header-wrapper.css:22:65: RightParenthesis is expected

> 22 |   background-image: url(header-wrapper.svg?inline_image=1);
     |                                                                 ^
```

**Comment by lahmatiy** [comment]
What version do you use?
I've just tried your line in CSSO web interface – it doesn't fail.

**Comment by rifler** [comment]
Sorry, probably mistake is in my `postcss-url` callback plus `postcss-svgo` plugin. They are called before `postcss-csso` and generates some strange stuff

**Comment by rifler** [comment]
but somehow error message contains old url, have no idea why
