### ISSUE TITLE
Failed on valid CSS syntax

### ISSUE THREAD

**Issue by demiazz** [css/csso#375]
Hi! Have a problem with minification of a bizarre type of selectors. For example:

```
div.--bizarre {
  background: red;
}
```

It's ugly, but it's legacy code and a valid CSS at the same time. Demo: https://jsfiddle.net/w566qLhg/

But if use `-` instead of `--` all looks to be OK.

Affected versions: `postcss-csso@3.0.0` with `csso@3.1.1` and standalone `csso@3.5.0`.

**Comment by LcpMarvel** [comment]
I got the same issue and found that `.--` is invalid for `csstree`.

You should validate your css and then compile it. https://github.com/csstree/validator

**Comment by lahmatiy** [comment]
That’s a bug in csstree and will be fixed soon

**Comment by lahmatiy** [comment]
Fixed in CSSO 4.0 and above.
