### ISSUE TITLE
Нельзя удалять % в hsl

### ISSUE THREAD

**Issue by Riim** [css/csso#382]
`hsl(0, 0, 10%)` -- это невалидное значение.

https://yadi.sk/i/Rm9o7PC03YneHV

**Comment by lahmatiy** [comment]
Looks like a problem occurs when percentage is using in TRBL properties:
![image](https://user-images.githubusercontent.com/270491/42977343-4dd177f6-8bcf-11e8-93d5-3cfade5f120d.png)

**Comment by lahmatiy** [comment]
The problem was with wrong percentage sign removal for zero values.
Fixed in CSSO 4.0.2
