### ISSUE TITLE
Сохранять хаки вида "w3c {} w3c, vendor {}"

### ISSUE THREAD

**Issue by afelix** [css/csso#39]
Сейчас CSSO угробит хаки вот такого вида:

    .my { color: red }
    .my, x:-vendor-pseudo { color: green }
до

    .my, x:-vendor-pseudo { color:green }
Пожалуй, единственный правильный вариант такое спасать — составить список всех вендорных селекторов, определять такие хаки и не перекрывать.

**Comment by lahmatiy** [comment]
Looks already fixed.
