### ISSUE TITLE
wrong restructure optimization with address tag

### ISSUE THREAD

**Issue by axten** [css/csso#392]
this rule gets removed:
```
address {
    font-style: normal;
}
```

but it is needed for browser reset, here because agent style is italic.
`restructure: false` fixed the issue...

**Comment by lahmatiy** [comment]
Can't reproduce with 4.0.2 (try [web interface](https://css.github.io/csso/csso.html)). Which version do you use? Does issue still exist?

**Comment by axten** [comment]
We use [postcss-csso](https://www.npmjs.com/package/postcss-csso), and with this, we have currently version 3.5.1

**Comment by lahmatiy** [comment]
Latest `postcss-csso` is using CSSO `^4.0.2`. Can we close an issue?

**Comment by axten** [comment]
sure :)
