### ISSUE TITLE
Restructure changes order of selectors with attributes

### ISSUE THREAD

**Issue by panec** [css/csso#396]
When CSSO restructure the CSS it does alphabetic sorting of the selectors that use attribute syntax `[class="..."]`

For the following code
```
.a [id=b],
[a_id=b] .a,
[id=b] .a,
.a.xyz {
    color: #000000
}

[class*=c] .a,
[class*=c] .a.xyz {
    color: #000000
}

```

The result is
```
.a [id=b],
.a.xyz,
[a_id=b] .a,
[class*=c] .a,
[class*=c] .a.xyz,
[id=b] .a {
	color: #000
}
```

When the expected one is
```
.a [id=b],
.a.xyz,
[a_id=b] .a,
[id=b] .a,
[class*=c] .a,
[class*=c] .a.xyz {
	color: #000
}
```

The selector `[id=b] .a,` is moved to the last position (after `[class*=c]` selector) just because the letter `i` is alphabetically after `c`

**Comment by lahmatiy** [comment]
That’s expected behaviour: some sort of normalization to make selector comparison cheap. What’s problem with it?

**Comment by panec** [comment]
Actually you are right, it does not matter what the order of the declarations is. This will work exactly the same way.
