### ISSUE TITLE
property: calc(var()) causes crash

### ISSUE THREAD

**Issue by jwagner** [css/csso#397]
Discovered this by accident. :)

## Steps to reproduce
* Open https://css.github.io/csso/csso.html
* Enter
```
div {
    margin-top: calc(var(margin-top) - 1px);
}
```
## Expected outcome
Nonsensical statement is either left alone or removed.

## Actual outcome
Error: `Cannot read property 'some' of undefined`

## Affected version
* Tested against 3.5.1

**Comment by lahmatiy** [comment]
Fixed. At least at 4.0.2 it's not reproducible.
