### ISSUE TITLE
Dependency has license incompatible with commercial usage: Upgrade to css-tree >= @alpha.30 

### ISSUE THREAD

**Issue by mistaecko** [css/csso#399]
`mdn-data@1.x` used the `MPL 2.0` license, which was subsequently changed to `CC0 1.0 Universal` in `mdn-data@2.x`.
Please bump to `css-tree@1.0.0-alpha.30` or later.

**Comment by caseprince** [comment]
Bump! (please and thank you!)

**Comment by lahmatiy** [comment]
Available as [v4.0.0](https://github.com/css/csso/releases/tag/v4.0.0)
