### ISSUE TITLE
Do not remove length unit for zero-values in min(), max() and clamp()

### ISSUE THREAD

**Issue by davidmondok** [css/csso#426]
CSSO should not remove px length unit for zero-values in min(), max() and clamp() CSS functions. 

The following minifies the 0px value to 0, which causes an invalid property value error in all the browsers I tested (Chrome, Firefox and Safari):

```css
margin-left: max(0px, (100% - 10rem)); // works

margin-left: max(0, (100% - 10rem)); // invalid property value
```

As a workaround one can simply write `0%` instead of `0px`, which won't get minified to `0`.

**Comment by lahmatiy** [comment]
Looks like it's easy to fix, we need check against a list of functions [here](https://github.com/css/csso/blob/86f2951fcf47ab59ad380c1430aaab8c91d8fbb9/lib/replace/Dimension.js#L46)
