### ISSUE TITLE
css math functions such as min(), max() and clamp() need to retain their spaces

### ISSUE THREAD

**Issue by MichaelDaum** [css/csso#433]
This is thankfully already the case for calc(). However
```
.foo {width: max(20vw, 400px);}
```
should become
```
.foo{width:max(20vw, 400px)}
```
and _not_
```
.foo{width:max(20vw,400px)}
```
Note the extra space after the comma.

**Comment by lahmatiy** [comment]
Could you please provide more details, why white spaces need to be retained in these cases? As I know white spaces inside a function is not required. The single exception is for white spaces around `+` and `-` inside `calc()` function. I missed something?
