### ISSUE TITLE
The negation pseudo-class If two selectors are used, they are omitted.

### ISSUE THREAD

**Issue by seunghun** [css/csso#436]
The negation pseudo-class If two selectors are used, they are omitted.

ex)
*:not(Foo, Foo2) 
--> null

![image](https://user-images.githubusercontent.com/764739/115406335-091aa780-a22a-11eb-82c9-c176e8a3690f.png)

**Comment by lahmatiy** [comment]
Can not to reproduce. Could you please provide a problem CSS instead of screenshot?
You may play with CSS and minification results in [web interface](https://css.github.io/csso/csso.html)

**Comment by seunghun** [comment]
After re-testing, it is assumed that this bug is caused by another module. Sorry
