### ISSUE TITLE
Хочется не склеивать значения со значениями, использующими инлайновые IE-хаки

### ISSUE THREAD

**Issue by kizu** [css/csso#46]
Есть два конкретных широко используемых хака для IE8/IE9 (например, [вот тут их упоминают](http://stackoverflow.com/questions/3890740/are-there-any-ie9-css-hacks)).

Первый, для IE8 и IE9, в конце свойства ставится конструкция ` \0/` (без пробела это правило поймёт ещё и опера):

    .a {
        color: lime;
        color: red \0/;
    }

Второй, только для IE9, в конце свойства пишется `\9`:

    .b {
        color: lime;
        color: red\9;
    }

Сейчас CSSO оставляет только второе значение, что логично. Но на практике было бы здорово знать, если эти правила поймут только соответствующие версии IE и не сжимать их.

**Comment by lahmatiy** [comment]
csso (like most others compressors) supports for `\9` (since it using by `bootstrap`) but no `\0/`. Believe it's enough and supporting for `\0/` is not actual.
