### ISSUE TITLE
Можно убирать несуществующие и никем не используемые свойства с префиксами

### ISSUE THREAD

**Issue by kizu** [css/csso#49]
Вспомнил пару моментов из доклада Пепелсбея про префиксы ([вот кадр](http://webstandardsdays.ru/2011/12/13/pres/pre-fixes/?full#CompassFail), например).

Смысл в том, что многие автоматические раскрыватели префиксных кластеров, а также многие верстальщики могут часто писать CSS3-свойство в префиком, которое в том или ином браузере не существует (т.е. изначально было реализовано без префикса). Это `-o-` и `-ms-` для `border-radius` и `box-shadow`, `-o-` для свойств `column-blah` и `background-size` и многие другие (хорошим источником для нахождения свойств, для которых никогда не существовало префиксов можно считать http://caniuse.com/).

Кажется, что совершенно безвредно было бы вырезать подобные конструкции из кода, скажем, вот такой вот кусок

    -webkit-box-shadow: 10px 10px 1px red;
       -moz-box-shadow: 10px 10px 1px red;
        -ms-box-shadow: 10px 10px 1px red;
         -o-box-shadow: 10px 10px 1px red;
            box-shadow: 10px 10px 1px red;

Можно было бы сократить до

    -webkit-box-shadow: 10px 10px 0 red;
       -moz-box-shadow: 10px 10px 0 red;
            box-shadow: 10px 10px 0 red;

(А если бы можно было гибко настраивать CSSO, то в теории можно было бы предусмотреть настройки поддерживаемых браузеров, тогда можно было бы исключать и `-khtml-` и `-webkit-` с `-moz-` для `border-radius` и `box-shadow`. Или и вовсе, для мобильных устройств вырезать всё кроме `-webkit-` и безпрефиксного варианта, а для .ie.css —вообще вырезать все CSS3-свойства)

Кстати, кажется, имеет смысл как-нибудь посмотреть на код, который генерят всякие SASS, Less, Compass и прочие, наверняка там можно попробовать найти ещё аналогичные места, которые можно сократить.

**Comment by lahmatiy** [comment]
I think it's not a task for csso (decide what properties are used or ever exists). It should just do safe optimizations for set of rules and properties, but not take in account usage or existence of smth.
Also today many developers use autoprefixer that make choice for prefixes set.
