### ISSUE TITLE
Хочется, чтобы CSSO мог сжимать все файлы в директории

### ISSUE THREAD

**Issue by kizu** [css/csso#56]
Для начала хочется какой-то ключ, который бы позволил перезаписывать файл результатом оптимизации.

А потом можно было бы сделать ключ, который бы позволил записать результат в «префикс + исходное имя файла». Ну и чтобы префикс мог быть и путём относительно текущего положения.

Тогда после всего этого можно было бы дать возможность сжимать всю папку (скажем, по умолчанию рекурсивно, а с ключём `-R` — не рекурсивно), используя такую команду: `csso . --rewrite` или `csso . --prefix _`, первая команда брала бы все файлы в директории и всех их сжимала, вторая — делала то же самое, но каждому файлу добавляла бы префикс: `style.css` превращался бы в `_style.css`.

Конечно, подобные вещи наверняка можно сделать и через что-то с грепом и xargs, но это не юзер-френдли :) И многие привыкли использовать «точку».

**Comment by lahmatiy** [comment]
Duplicates #97

**Comment by lahmatiy** [comment]
I believe that the file concatenation task is for task runners. Btw, CLI was extracted into separate project and the issue isn't relevant for this repo anymore, sorry.
