### ISSUE TITLE
Links to https://github.com/afelix/csso/

### ISSUE THREAD

**Issue by kizu** [css/csso#62]
While the previous location is somewhat heavily linked in the internets, it would be nice to have there something to redirect to the @css/csso.

One of the possible easy solutions is to fork the @css/csso to @afelix, then delete everything here except the `README.md`, in what you'd write that the repo is moved.

So there would be some places with link to the @css/csso — the readme, the github's “forked from …” link, and the project's link, where you could also add the link to the new repo's location.

Also, it would be nice to replace the content of `gh-pages` with the pages with links and redirects, like explained [here](http://stackoverflow.com/a/5411601/885556).

**Comment by lahmatiy** [comment]
I believe it's not an issue now.
