### ISSUE TITLE
An error in CSS leads to an error in CSSO

### ISSUE THREAD

**Issue by kizu** [css/csso#84]
If there is a single dot in a selector, CSSO throws an error. So line like

``` CSS
.xgd,.xdk,.x6v,.,.xyf,.,.,.WCMediumBackground,. {}
```

Would pervent a stylesheet to be optimised, however, while it's the error in the CSS, the following styles would be parsed: http://dabblet.com/gist/3849719

(this example was got from this gist — https://raw.github.com/gist/3849632/f02d8beb2ccfd492fc4df4e0a9552f30eb5173c3/poetry.css)

**Comment by lahmatiy** [comment]
First example is incorrect CSS.
`._0 { width: 10px; }` is ok to parse now.
